# Generated by Django 3.2.4 on 2021-09-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user1ReadAt',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user2ReadAt',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
